dist: xenial

addons:
  snaps:
    - name: snapcraft
      channel: beta/remote-build
      confinement: clasic

before_script:
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - cat "$SSH_KEY" > ~/.ssh/id_rsa
  # Launchpad host key
  - echo "|1|E2auap4gDHOhHerCFAdqNHrIljY=|4C3Xxrcp76Ls3Wj2NwNsNTNwfgE= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEFREwBD2ye2Xrc2SVcUmmJ44MF1BCB3W11NTaiqzVj7XZnQmgWZk9UadHVY2wBXvelcDO51MPN5ozJjFAknw09rP7XMRJMlAOLSIVoU6DRF1u1j8kJVY+dfiDHheS7+siADnrmb8HGn2xQQ6EJDjAXrw1x58x5eZjQ0PFWdI+pRTdYGvWkpHdXKFO6a9/lDx4uo9MCnePEGi/QnkCmKqLCBUlYNZYRiB8nVee2tMF0mjV8xk1rJ+/UP+897+FXFR9w/B1EPRjiQ35ZNQZKPP4isxPtyMuCQkZY7ckWr5YsylNfvNcyGDnO1XazZhJ71rzDpi1RmnFXBW5i+2dm2y7
" > ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/*
  - chown -R $USER ~/.ssh
  -
script:
  - snapcraft remote-build --arch s390x
