name: matrix-server
base: core20
confinement: strict
architectures:
  - build-on: amd64

adopt-info: synapse
summary: Reference implementation matrix server.
description: |
  Synapse is a reference "homeserver" implementation of Matrix from the core
  development team at matrix.org, written in Python/Twisted. It is intended
  to showcase the concept of Matrix and let folks see the spec in the context
  of a codebase and let you run your own homeserver and generally help bootstrap
  the ecosystem.

apps:
  synapse:
    command: synapse start
    daemon: forking
    stop-command: synapse stop
    adapter: full
    plugs:
      - network
      - network-bind
  mautrix-whatsapp:
    command: mautrix-whatsapp
    daemon: simple
    adapter: full
    plugs:
      - network
      - network-bind
  register-new-user:
    command: bin/register_new_matrix_user
    adapter: full
    plugs:
      - network

parts:
  scripts:
    source: .
    plugin: dump
  synapse:
    source: https://github.com/matrix-org/synapse.git
    source-type: git
    plugin: python
    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      [ -n "$(echo "$version" | grep "+git")" ] && grade=devel || grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
    stage-packages:
      - git
    build-packages:
      - git
  mautrix-whatsapp:
    source: https://github.com/tulir/mautrix-whatsapp.git
    plugin: go
    build-packages:
      - gcc
      - libolm-dev
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bridges/mautrix-whatsapp
      install example-config.yaml $SNAPCRAFT_PART_INSTALL/bridges/mautrix-whatsapp/example-config.yaml
